name: printing-secrets
on: [push]

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: echo "hello world"
      
      - name: print-secrets
        run: echo "REPO_SECRET_KEY_1: ${{ secrets.REPO_SECRET_KEY_1 }}"